create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  body text not null,
  seo_title text,
  seo_description text,
  is_published boolean not null default false,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.navigation_links (
  id bigint generated by default as identity primary key,
  label text not null,
  url text not null,
  position integer not null default 0,
  is_external boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved', 'closed')),
  handled_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'subscribed' check (status in ('subscribed', 'unsubscribed')),
  subscribed_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  event_payload jsonb not null default '{}'::jsonb,
  page_url text,
  referrer text,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_pages_slug on public.pages (slug);
create index if not exists idx_pages_published on public.pages (is_published);
create index if not exists idx_navigation_links_position on public.navigation_links (position);
create index if not exists idx_contact_submissions_status on public.contact_submissions (status);
create index if not exists idx_newsletter_subscribers_status on public.newsletter_subscribers (status);
create index if not exists idx_site_events_event_name on public.site_events (event_name);
create index if not exists idx_site_events_created_at on public.site_events (created_at);

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_pages_updated_at
before update on public.pages
for each row execute function public.set_updated_at();

create trigger set_navigation_links_updated_at
before update on public.navigation_links
for each row execute function public.set_updated_at();

create trigger set_contact_submissions_updated_at
before update on public.contact_submissions
for each row execute function public.set_updated_at();

create trigger set_newsletter_subscribers_updated_at
before update on public.newsletter_subscribers
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.pages enable row level security;
alter table public.navigation_links enable row level security;
alter table public.contact_submissions enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.site_events enable row level security;

create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (auth.uid() = id or exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "profiles_update_own_or_admin"
on public.profiles
for update
to authenticated
using (auth.uid() = id or exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
))
with check (auth.uid() = id or exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "pages_select_published"
on public.pages
for select
to anon, authenticated
using (is_published = true or exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "pages_admin_write"
on public.pages
for all
to authenticated
using (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
))
with check (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "navigation_links_select_active"
on public.navigation_links
for select
to anon, authenticated
using (is_active = true or exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "navigation_links_admin_write"
on public.navigation_links
for all
to authenticated
using (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
))
with check (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "contact_submissions_insert"
on public.contact_submissions
for insert
to anon, authenticated
with check (true);

create policy "contact_submissions_admin_read_write"
on public.contact_submissions
for all
to authenticated
using (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
))
with check (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "newsletter_subscribers_insert"
on public.newsletter_subscribers
for insert
to anon, authenticated
with check (status = 'subscribed');

create policy "newsletter_subscribers_admin_read_write"
on public.newsletter_subscribers
for all
to authenticated
using (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
))
with check (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create policy "site_events_insert"
on public.site_events
for insert
to anon, authenticated
with check (true);

create policy "site_events_admin_read"
on public.site_events
for select
to authenticated
using (exists (
  select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'
));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
